# Generated by Django 2.2.5 on 2019-10-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_maincontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincontent',
            old_name='content',
            new_name='article_content',
        ),
    ]
