# Generated by Django 2.2.5 on 2019-10-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20191025_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='mc_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
